version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Capturing the AWS CLI and Python versions used in this build."
            - aws --version
            - python --version
    pre_build:
        commands:
    build:
        commands:
            - echo Build started on `date`
            - zip -r -j hw3_1323_lambda.zip src/hw3_lambda.py src/util.py
    post_build:
        commands:
            - echo Build completed on `date`
            - echo "Updating lambda function code."
            - aws lambda update-function-code --function-name "hw3-lambda-function" --zip-file fileb://./hw3_1323_lambda.zip
artifacts:
    name: hw3_1323_lambda_build
    files:
        - 'appspec.yml'
        - 'hw3_1323_lambda.zip'
    discard-paths: yes