AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creates CodeBuild Resource Stack for Homework #3'
Resources:

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'hw3-1323-artifacts'
      VersioningConfiguration:
        Status: Suspended

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Statement:
          -
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${ArtifactsBucket}/*
            Principal: '*'

  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: hw3-layers-build
      Description: Build and publish HW3 lambda layers
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/hw3-code-pipeline-service-role
      Artifacts:
        Type: S3
        Name: '/'
        Location: !Ref ArtifactsBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: GITHUB
        Location: https://github.com/steveviens/deepak-hw3.git      # TODO: Replace this with your GitHub repo
        BuildSpec: 'buildspec/layers_buildspec.yml'
      #Triggers:
      #  BuildType: BUILD
      #  Webhook: True
      #  FilterGroups:
      #  - - Type: EVENT
      #      Pattern: PUSH
      TimeoutInMinutes: 10


