# REF: AmazonSageMaker-ExecutionRole-20211217T204269
# Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpoint.html

AWSTemplateFormatVersion: "2010-09-09"
Description: "Basic Hosting entities test.  We need models to create endpoint configs."

Parameters:

  PredictionEndpointParameter:
    Type: String
    Description: HW3 Prediction Endpoint
    Default: "replace_with_prediction_endpoint"

Mappings: 

  # List (Map) of continers referenced by AWS region name from the SageMakerModel resource below
  RegionMap:
    "us-east-1":
      "NullTransformer": "811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest"

Resources:

  SageMakerEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointName: hw3-sagemaker-endpoint
      EndpointConfigName:
        !GetAtt SageMakerEndpointConfig.EndpointConfigName

  SageMakerEndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      EndpointConfigName: hw3-sagemaker-endpoint-config
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: ml.t2.large
          ModelName: !GetAtt SageMakerModel.ModelName
          VariantName: !GetAtt SageMakerModel.ModelName

  SageMakerModel:
    Type: "AWS::SageMaker::Model"
    Properties:
      ModelName: hw3-sagemaker-model
      PrimaryContainer:
        Image: !FindInMap [RegionMap, !Ref "AWS::Region", "NullTransformer"]
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn

  SageMakerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: hw3-sagemaker-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - sagemaker.amazonaws.com
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonSageMakerFullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonS3FullAccess

Outputs:

  EndpointId:
    Value: !Ref SageMakerEndpoint

  EndpointName:
    Value: !GetAtt  SageMakerEndpoint.EndpointName