version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Capturing the AWS CLI and Python versions used in the build."
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo "Installing 3rd party Python modules"
            - pip install -r requirements.txt
    build:
        commands:
            - echo Building hw3 lambda - started on `date`
            - zip -r -j predict_spam_function.zip src/predict_spam_function.py
    post_build:
        commands:
            - echo Build completed on `date`
            - echo "Updating lambda function code."
            - aws lambda update-function-code --function-name "hw3-predict-spam-function" --zip-file fileb://./predict_spam_function.zip

# REFERENCE:
#   - Build specification reference for CodeBuild
#     https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
