version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo Build starting on `date`
              echo Capturing the AWS CLI and Python versions used in the build
            - aws --version
            - python --version
    pre_build:
        commands:
            - echo Create a Python virtual environment
            - python3 -m venv ./venv
            - echo Start the Python virtual environment
            - source ./venv/bin/activate
            - echo Updating pip
            - pip install --upgrade pip
    build:
        commands:
            - echo Downloading python modules
            - pip install -t numpy/python numpy
            - pip install -t requests/python requests
    post_build:
        commands:
            - echo Packaging python modules into zip files
            - (cd numpy; zip -r ../hw3-numpy-layer.zip python)
            - (cd requests; zip -r ../hw3-requests-layer.zip python)
            - echo Build completed on `date`
artifacts:
    files:
        - hw3-numpy-layer.zip
        - hw3-requests-layer.zip

# REFERENCE:
#   - Build specification reference for CodeBuild
#     https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
